
spring:
  # \u914D\u7F6E\u6570\u636E\u6E90\u4FE1\u606F
  datasource:
    # \u914D\u7F6E\u6570\u636E\u6E90\u7C7B\u578B
    type: com.zaxxer.hikari.HikariDataSource
    # \u914D\u7F6E\u8FDE\u63A5\u6570\u636E\u5E93\u7684\u5404\u4E2A\u4FE1\u606F
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/gamelive?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
#    password: 354172
    password: 123456

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #\u5F00\u542Fsql\u65E5\u5FD7
    devtools:
      restart:
        enabled: true
        additional-paths: src/main
        exclude: static/**
server:
  port: 8008

#files:
#  upload:
#    path: D:/\u3002\u3002\u3002/EE/travelDemo/src/main/resources/static/images

#HealMe测试区
files:
  upload:
    path: D:\Desktop\canyon_images




