spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/gamelive?useUnicode=true&useSSL=false&characterEncoding=utf8
    #    url: jdbc:mysql://localhost:3306/gamelive?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    #    password: 354172
    password: 123456

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    devtools:
      restart:
        enabled: true
        additional-paths: src/main
        exclude: static/**
server:
  port: 8008

live-room:
  open-live:
    #直播服务器推流地址
    server-address: rtmp://192.168.159.130:1935/live
    flv-url: http://192.168.159.130:8080/live

#HealMe测试区
files:
  upload:
    path: D:\Desktop\canyon_images




